php:
  container_name: web
  build: docker/php/
  #ports:
  #  - 9000:9000
  links:
    - redis
    - mongo
  volumes:
    - ./code:/var/www
  environment:
    APP_SERVER_NAME: App

nginx:
  container_name: nginx
  build: docker/nginx/
  ports:
    - 8080:80
  links:
    - php
  volumes_from:
    - php
  environment:
    APP_SERVER_NAME: App

mongo:
  container_name: mongodb
  build: docker/mongo/
  ports:
    - 27017:27017
  volumes:
    - /srv/docker/mongodb:/var/lib/mongodb
    - ./data/db:/data/db
    - ./data/configdb:/data/configdb
  environment:
    POSTGRES_PASSWORD: admin
    POSTGRES_USER: admin
    POSTGRES_DB: symfony

redis:
  container_name: redis
  image: redis:latest
